#!/usr/bin/env python3
"""
Mine MIMIC-CXR + MIMIC-IV-Note radiology reports into weighted phrase lists
for Apple's SFCustomLanguageModelData.

Input : data/raw/  (from download_mimic.sh)
Output: output/phrases_<modality>.json  +  output/Phrases.swift

Stdlib only. Run after download_mimic.sh.
"""
import csv
import gzip
import json
import re
import sys
import zipfile
from collections import Counter
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
RAW = BASE / "data" / "raw"
OUT = BASE / "output"
OUT.mkdir(exist_ok=True)

MAX_N = 3          # n-grams up to trigrams
MIN_COUNT = 25     # drop ultra-rare phrases (tune later)

SECTION_RE = re.compile(r"^\s*(EXAM|INDICATION|HISTORY|TECHNIQUE|COMPARISON|FINDINGS|IMPRESSION)\s*:?\s*$", re.I)
SENT_SPLIT = re.compile(r"(?<=[.;])\s+")
TOKEN_RE = re.compile(r"[a-zA-Z][a-zA-Z\-']+")
NUM_TOKEN = "<NUM>"

# Modality detection for MIMIC-IV-Note free text
MODALITY_PATTERNS = [
    ("xr",   re.compile(r"\b(x[- ]?ray|chest pa|frontal|lateral view|radiograph)\b", re.I)),
    ("ct",   re.compile(r"\b(ct|cat scan|computed tomography|non ?contrast)\b", re.I)),
    ("mr",   re.compile(r"\b(mri|mr |magnetic resonance)\b", re.I)),
    ("us",   re.compile(r"\b(ultrasound|sonogram|doppler|echocardiogram)\b", re.I)),
]


def normalize(text: str) -> str:
    text = text.lower()
    text = re.sub(r"\d+(\.\d+)?", NUM_TOKEN, text)
    return text


def tokens_to_sentence_tokens(sentence: str):
    toks = TOKEN_RE.findall(sentence.replace(".", " . "))
    out = []
    for t in toks:
        if t == ".":
            continue
        if t.isdigit():
            out.append(NUM_TOKEN)
        else:
            out.append(t.lower())
    return out


def add_ngrams(counter: Counter, sentence: str):
    toks = tokens_to_sentence_tokens(sentence)
    for n in range(1, MAX_N + 1):
        for i in range(len(toks) - n + 1):
            gram = " ".join(toks[i:i + n])
            if len(gram.strip()) < 4:
                continue
            counter[gram] += 1


# ---------------- MIMIC-CXR (.txt files inside reports.zip) ----------------
def mine_mimic_cxr(zip_path: Path, counters: dict):
    with zipfile.ZipFile(zip_path) as z:
        names = [n for n in z.namelist() if n.endswith(".txt")]
        print(f"MIMIC-CXR: {len(names)} report files")
        for name in names:
            text = z.read(name).decode("utf-8", errors="ignore")
            for line in text.splitlines():
                if SECTION_RE.match(line):
                    continue
                for sent in SENT_SPLIT.split(line):
                    sent = sent.strip()
                    if 20 < len(sent) < 300:
                        add_ngrams(counters["cxr"], normalize(sent))


# ------------- MIMIC-IV-Note radiology module (csv.gz, all modalities) -------------
def mine_iv_note(path: Path, counters: dict):
    opener = gzip.open if path.suffix == ".gz" else open
    total = 0
    with opener(path, "rt", encoding="utf-8", errors="ignore") as f:
        reader = csv.DictReader(f)
        for row in reader:
            text = (row.get("note_text") or row.get("text") or "")
            if not text:
                continue
            total += 1
            modality = next((m for m, pat in MODALITY_PATTERNS if pat.search(text[:400])), "other")
            # First 400 chars usually contain exam/indication; findings live throughout.
            for para in text.split("\n"):
                for sent in SENT_SPLIT.split(para):
                    sent = sent.strip()
                    if 20 < len(sent) < 300:
                        key = f"iv_{modality}"
                        add_ngrams(counters.setdefault(key, Counter()), normalize(sent))
    print(f"MIMIC-IV-Note: {total} radiology notes")


def dump(counter: Counter, name: str):
    phrases = [
        {"phrase": p, "count": c}
        for p, c in counter.most_common()
        if c >= MIN_COUNT and p.strip() != NUM_TOKEN
    ]
    out_file = OUT / f"phrases_{name}.json"
    out_file.write_text(json.dumps(phrases, indent=1))
    print(f"  {name}: {len(phrases):,} phrases -> {out_file.name}")
    return phrases


def gen_swift(all_phrases: dict):
    lines = [
        "// AUTO-GENERATED by mine_reports.py — do not edit by hand.",
        "// Derived statistics only; contains no source text.",
        "import Speech",
        "",
        "enum RadiologyCorpus {",
        "    static func customModelData(version: String) -> SFCustomLanguageModelData {",
        '        SFCustomLanguageModelData(',
        '            locale: Locale(identifier: "en_US"),',
        '            identifier: "com.radiologyasr.corpus\\(version)",',
        '            version: version',
        '        ) {',
    ]
    for name, phrases in all_phrases.items():
        lines.append(f"            // MARK: {name}")
        for p in phrases[:20000]:  # keep bundle size sane
            esc = p["phrase"].replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'            .PhraseCount("{esc}", {p["count"]})')
    lines += ["        }", "    }", "}"]
    swift = "\n".join(l.replace(".PhraseCount(", "SFCustomLanguageModelData.PhraseCount(")
                      if l.lstrip().startswith('.PhraseCount') else l for l in lines)
    (OUT / "Phrases.swift").write_text(swift)
    print(f"Swift source -> {OUT / 'Phrases.swift'}")


def main():
    counters: dict = {"cxr": Counter()}
    cxr_zip = RAW / "mimic_cxr_reports.zip"
    iv_note = RAW / "mimic_iv_note_radiology.csv.gz"

    if cxr_zip.exists():
        mine_mimic_cxr(cxr_zip, counters)
    else:
        print("!! mimic_cxr_reports.zip not found — skipping")

    if iv_note.exists():
        mine_iv_note(iv_note, counters)
    else:
        print("!! mimic_iv_note_radiology.csv.gz not found — skipping")

    if all(c.total() == 0 for c in counters.values()):
        sys.exit("Nothing mined. Run scripts/download_mimic.sh first.")

    print("\nPhrase extraction:")
    all_phrases = {name: dump(c, name) for name, c in sorted(counters.items())}
    gen_swift(all_phrases)


if __name__ == "__main__":
    main()
